TSService portability
1. Allow nodejs to be named "node"

2. Use --harmony instead of --harmony_collections
   Newer versions of nodejs (v0.11.15+) always have the ES6 collections
   enabled and do not recognize --harmony_collections.

3. Don't use stderr inheritance.
   Netbeans may be run without a console in which case there is no
   stderr. On Windows, if nodejs doesn't have a stderr, it will throw
   an exception when the .stderr property on process is read:

       Error: Implement me. Unknown stream file type!
           at createWritableStdioStream (node.js:603:15)
           at process.stderr (node.js:634:16)

   Make stderr another pipe (closed immediately to prevent deadlocks),
   and log messages over stdout instead.